***
## 예외와 예외 클래스
컴퓨터 하드웨어의 고장으로 인해 응용프로그램 실행 오류가 발생하는 것을 자바에서는 에러라고 한다.</br>
프로그램을 아무리 견고하게 만들어도 개발자는 이런 에러에 대처할 방법이 전혀 없다</br>

자바에서는 에러 이외에 예외라고 부르는 오류가 있다. 예외란 잘못된 사용 또는 코딩으로 인한 오류를 말한다.</br>
예외가 발생되면 프로그램은 곧바로 종료된다는 점에서는 에러와 동일하지만, 예외 처리를 통해 계속 실행 상태를 </br>
유지할 수 있다. 예외에는 다음 두 가지가 있다.</br>

* 일반 예외(Exception)
  * 컴파일러가 예외 처리 코드 여부를 검사하는 예외를 말한다.

* 실행 예외(Runtime Exception)
  * 컴파일러가 예외 처리 코드 여부를 검사하지 않는 예외를 말한다.
</br>
자바는 예외가 발생하면 예외 클래스로부터 객체를 생성한다. 이 객체는 예외 처리 시 사용된다. </br>
자바의 모든 에러와 예외 클래스는 Throwable을 상속받아 만들어지고, 추가적으로 예외 클래스는 </br>
java.lang.Exception 클래스를 상속받는다.

***
## 예외 처리 코드
예외가 발생했을 때 프로그램의 갑작스러운 종료를 막고 정상 실행을 유지할 수 있도록 처리하는 </br>
코드를 예외 처리 코드라고 한다. 예외 처리 코드는 try-catch-finally 블록으로 구성된다. </br>
try-catch-finally 블록은 `생성자 내부`와 `메서드 내부`에서 작성된다. 

* 정상 실행되었을 경우
  아래의 로직에서 catch 블록은 생략하고 넘어간다.
* 예외가 발생되었을 경우
  아래의 로직에 try 블록에서 예외가 발생한 줄 부터 멈추고 catch 블록으로 넘어가서 예외를 처리한다.
```
try{
  예외 발생 가능 코드
}catch(예외클래스 e){
  예외 처리
}finally{
  항상 실행;
}
```
try 블록에서 작성한 코드가 예외 없이 정상 실행되면 catch 블록은 실행되지 않고 finally 블록이 </br>
실행된다.  그러나 try 블록에서 예외가 발생하면 catch 블록이 실행되고 연이어 finally 블록이 실행된다. </br>

예외 발생 여부와 상관없이 finally 블록은 항상 실행된다. 심지어 try 블록과 catch 블록에서 </br>
return 문(메서드 종료)을 사용하더라도 finally 블록은 항상 실행된다. finally 블록은 옵션으로 </br>
생략 가능


처리해야 할 예외 클래스들이 상속 관계에 있을 때는 하위 클래스 catch 블록을 먼저 작성하고 </br>
상위 클래스 catch 블록을 나중에 작성해야 한다. 예외가 발생하면 catch 블록은 위에서부터 </br>
차례대로 검사 대상이 되는데, 하위 예외도 상위 클래스 타입이므로 상위 클래스 catch 블록이 먼저 </br>
검사 대상이 되면 안된다 .</br>
`잘못된 예`
```
try {
  ArrayIndexOutOfBoundsException 발생

  NumberFormatException 발생

}catch(Exception) {
  예외처리1
}catch(ArrayIndexOutOfBoundsException e) {
  예외처리2
}
```

***
## 예외 떠넘기기
메서드 내부에서 예외가 발생할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, </br>
메서드를 **호출한**곳으로 예외를 떠넘길 수도 있다. 이때 사용하는 키워드가 throws이다. </br>
throws는 메서드 선언부 끝에 작성하는데, 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.</br>
```
리턴타입 메서드명(매개변수,...) throws 예외클래스1, 예외클래스2 {
}
```

throws 키워드가 붙어 있는 메서드에서 해당 예외를 처리하지 않고 떠넘겼기 때문에 이 메서드를 </br>
**호출하는 곳에서** 예외를 받아 처리해야 한다. </br>
예를 들어 다음 코드는 ClassNotFoundException을 throws하는 method2()의 예외를 method1()에서 </br>
호출할 때 처리하고 있다. 
```
public void method1() {
  try{
    method2() //method2() 호출
  }catch(ClassNotFoundException e) {
    System.out.println("예외 처리: " + e.getMessage()); //호출한 곳에서 예외 처리
  }
}

public void method2() throws ClassNotFoundException {
  Class.forName("java.lang.String2");
}
```

나열해야 할 예외 클래스가 많을 경우에는 throws Exception 또는 throws Throwable 만으로 모든 예외를 </br>
간단히 떠넘길 수도 있다.

main() 메서드에서도 throws 키워드를 상요해서 예외를 떠넘길 수 있는데, 결국 **JVM**이 최종적으로 </br>
예외 처리를 하게 된다. JVM은 예외의 내용을 콘솔에 출력하는 것으로 예외 처리를 한다. 

***
## 사용자 정의 예외
은행의 뱅킹 프로그램에서 잔고보다 더 많은 출금 요청이 들어온 경우에는 잔고 부족 예외를 발생</br>
시킬 필요가 있다. 그러나 잔고 부족 예외는 표준 라이브러리에는 존재하지 않기 때문에 직접 예외 </br>
클래스를 정의해서 사용해야 한다. 이것을 **사용자 정의 예외**라고 한다.</br>

사용자 정의 예외는 컴파일러가 체크하는 일반 예외로 선언할 수도 있고, 컴파일러가 체크하지 않는</br>
실행 예외로 선언할 수 있다. 통상적으로 일반 예외는 Exception의 자식 클래스로 선언하고, 샐행 예외는 </br>
RuntimeException의 자식 클래스로 선언한다.
```
public class XXXException extends [Exception | RuntimeException ] {
  public XXXException() { //기본 생성자
  }

  public XXXException(String message) { //예외 메시지를 입력받는 생성자
    super(message);
  }
}
```
사용자 정의 예외 클래스에는 기본 생성자와 예외 메시지를 입력받는 생성자를 선언해준다. </br>
예외 메시지는 부모 생성자 매개값으로 넘겨주는데 그 이유는 예외 객체의 공통 메서드인 getMessage()의</br>
리턴값으로 사용하기 위해서이다.</br>

throw된 예외는 직접 try-catch 블록으로 예외를 처리할 수도 있지만, 대부분은 메서드를 호출한 곳에서 </br>
예외를 처리하도록 throws 키워드로 예외를 떠넘긴다.

### 예제로 이해하기
은행 계좌(Account) 클래스의 출금(withdraw) 메서드에서 잔고(balance) 필드와 출금액(매개값)을 </br>
비교해 잔고가 부족하면 InsufficientException을 발생시키고 throws한다. </br>
그리고 AccountExample은 withdraw() 메서드를 호출할 때 예외 처리를 한다. </br>

```
public class Account {
  private long balance;

  public Account() {}

  public long getBalance() {
    return balance;

  public void deposit(int money) {
    balance += money;
  }

  public void withdraw(int money) throw InsufficientException {
    if(balance < money ) {
      throw new InsufficientException("잔고 부족 : " + (money-balance) + " 모자람");
    }
    balance -= money;
  }
  }
}
```

```
public class AccountExample {
  public static void main(String[] args){
    Account account = new Account();

    //예금하기
    account.deposit(10000);
    System.out.println("예금액 : " + account.getBalance());

    //출금하기
    try{
      account.withdraw(30000);
    }catch(InsufficientException e) {
      Stirng message = e.getMessage();
      System.out.println(message);
    }
  }
}
```
**실행결과**
****
예금액 : 10000
잔고 부족: 20000 모자람

***
## 오버라이딩된 메서드와 예외처리
자바에서 오버라이딩된 메서드가 예외를 던질 수 있는지에 대한 여부는 몇 가지 규칙이 있다.</br>
1. Checked Exception:
   오버라이딩된 메서드는 원본 메서드에서 던지는 체크드 예외와 동일한 예외를 던지거나, </br>
   그 예외의 하위 클래스만 던딜 수 있다. 즉, 오버라이딩된 메서드는 원본 메서드가 던질 </br>
   수 잇는 예외보다 더 넒은 범위의 체크드 에외를 던질 수 없다.
2. Unchecked Exception:
   언체크드 예외(RuntimeException 및 그 하위 클래스)는 오버라이딩 된 메서드에서 </br>
   자유롭게 던질 수 있다. 원본 메서드가 언체크드 예외를 던지지 않더라도, 오버라이딩된 </br>
   메서드에서 새로운 언체크드 예외를 던질 수 있다.
3. 오버라이딩 규칙 요약:
   * 오버라이딩된 메서드는 원본 메서드에서 던지는 체크드 예외와 동일하거나 더 구체적인 체크드 예외를 던질 수 있다.
   * 원본 메서드가 던지지 않는 체크드 예외를 새롭게 던질 수 없다.
   * 언체크드 예외는 자유롭게 던질 수 있다.
